import { ReactNode, useEffect } from "react";
import classes from "./Layout.module.sass";
import Head from "next/head";
import SystemInfo from "../SystemInfo";
import { isDevelop } from "@/utils/isDevelop";
import Reset from "./Reset";
import { useDispatch, useSelector } from "react-redux";
import { select } from "@/store/select";
import { useRouter } from "next/router";
import { setLocale } from "@/store/app/app.actions";
import { getLocale } from "translate/locales";
import Language from "./Language";

interface LayoutProps {
    children: ReactNode;
    pageName?: string;
}

const Layout = ({ children, pageName }: LayoutProps) => {

    const router = useRouter();
    const dispatch = useDispatch();

    const locale = router.locale;


    useEffect(() => {
        dispatch(setLocale(getLocale(locale)))
    }, [dispatch, locale])

    return (
        <div className={classes.page_container}>
            <Head>
                <title>{pageName || "Codenames"}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

                {isDevelop() && <Reset />}
                {children}
                <SystemInfo />
                <Language />
            </main>
            {/* {processing && <Loading />} */}
        </div>
    );
};

export default Layout;
