import { ReactNode } from 'react';
import classes from './Layout.module.sass';
import Head from 'next/head';
import Chat from '../Chat';

interface LayoutProps {
    children: ReactNode,
    pageName?: string
}

const Layout = ({ children, pageName }: LayoutProps) => {

    return (
        <div className={classes.page_container}>
            <Head>
                <title>{pageName || "Codenames"}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

                <Chat />
                {children}
            </main>
        </div>
    );


};

export default Layout;